  services:
    mysql-container:
      image: mysql:latest
      ports:
      - "3307:3306"
      volumes:
      - ./docker/volume_mysql:/var/lib/mysql # Monta un volumen para persistencia de datos
      container_name: src
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test_db